# Generated by Django 3.1 on 2025-07-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_category_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
    ]
