# Generated by Django 3.1 on 2025-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250717_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='storageitem',
            name='modification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модификация'),
        ),
    ]
