# Generated by Django 3.1 on 2025-07-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20250721_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageitem',
            old_name='modification',
            new_name='description',
        ),
    ]
