# Generated by Django 3.1 on 2025-07-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20250721_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Модификация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='main.product')),
            ],
            options={
                'verbose_name': 'Модификация товара',
                'verbose_name_plural': 'Модификации товаров',
            },
        ),
    ]
