# Generated by Django 3.1 on 2025-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20250724_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='productmodification',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
