# Generated by Django 3.1 on 2025-07-31 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifications',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.ProductModification'),
        ),
        migrations.AlterField(
            model_name='productmodification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_set', to='main.product'),
        ),
    ]
