# Generated by Django 3.1 on 2025-07-31 03:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20250731_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Модификации'),
        ),
        migrations.DeleteModel(
            name='ProductModification',
        ),
    ]
